# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_win64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_win64)
  Batch_config = debug_win64

else ifeq ($(config),debug_win32)
  Batch_config = debug_win32

else ifeq ($(config),debug_linux32)
  Batch_config = debug_linux32

else ifeq ($(config),debug_linux64)
  Batch_config = debug_linux64

else ifeq ($(config),release_win64)
  Batch_config = release_win64

else ifeq ($(config),release_win32)
  Batch_config = release_win32

else ifeq ($(config),release_linux32)
  Batch_config = release_linux32

else ifeq ($(config),release_linux64)
  Batch_config = release_linux64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Batch

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Batch:
ifneq (,$(Batch_config))
	@echo "==== Building Batch ($(Batch_config)) ===="
	@${MAKE} --no-print-directory -C . -f Batch.make config=$(Batch_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Batch.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_win64"
	@echo "  debug_win32"
	@echo "  debug_linux32"
	@echo "  debug_linux64"
	@echo "  release_win64"
	@echo "  release_win32"
	@echo "  release_linux32"
	@echo "  release_linux64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Batch"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"